#!/usr/bin/env python3
import ioutil
import argparse
import sys
import os.path as path
import re
import io

g_alignment: int = 4
g_output_mode: str = "default"
g_symbol_prefix: str = ""


# generate ARM/x86 assembly source file
def generate_default(name: str, data: bytes) -> None:
    out = sys.stdout
    symbol_name = g_symbol_prefix + name

    out.write("/* Generated by BIN2S - please don't edit directly */\n")
    out.write(f"\t.section    .rodata.{name},\"a\"\n")
    out.write(f"\t.global     {symbol_name}\n")
    out.write(f"\t.balign     {g_alignment}\n")
    out.write(f"{symbol_name}:\n")

    idx: int = 0
    for byte in data:
        if idx % 16 == 0:
            if idx != 0: out.write("\n")
            out.write("\t.byte       ")
        else:
            out.write(",")

        out.write(str(byte).rjust(3))
        idx += 1
    
    out.write("\n\n")
    out.write("\n")

    #out.write(f"\t.section    .rodata.{name}_end,\"\",@\n")
    out.write(f"\t.global     {symbol_name}_end\n")
    out.write(f"{symbol_name}_end:\n")


# generate WASM source file that can be read by clang
# (this is not WAT)
def generate_wasm(name: str, data: bytes) -> None:
    out = sys.stdout
    symbol_name = g_symbol_prefix + name

    out.write("/* Generated by BIN2S - please don't edit directly */\n")
    out.write(f"\t.section    .rodata.{name},\"\",@\n")
    out.write(f"\t.globl      {symbol_name}\n")
    out.write(f"\t.p2align    {g_alignment},0x0\n")
    out.write(f"{symbol_name}:\n")

    idx: int = 0
    for byte in data:
        if idx % 16 == 0:
            if idx != 0: out.write("\n")
            out.write("\t.byte       ")
        else:
            out.write(",")

        out.write(str(byte).rjust(3))
        idx += 1
    
    out.write("\n")
    out.write(f"\t.size       {symbol_name},{len(data)}\n")
    out.write("\n")

    #out.write(f"\t.section    .rodata.{name}_end,\"\",@\n")
    out.write(f"\t.globl      {symbol_name}_end\n")
    out.write(f"{symbol_name}_end:\n")
    out.write(f"\t.size       {symbol_name}_end,0\n")


def process_file(name: str, ifile: io.BufferedReader, ofile_h: io.TextIOWrapper) -> None:
    bytes = ifile.read()

    match g_output_mode:
        case "default":
            generate_default(name, bytes)
        case "wasm":
            generate_wasm(name, bytes)

    if ofile_h:
        ofile_h.write(f"extern const uint8_t {name}[];\n")
        ofile_h.write(f"extern const uint8_t {name}_end[];\n")
        ofile_h.write("#if __cplusplus >= 201103L\n")
        ofile_h.write(f"static constexpr size_t {name}_size={len(bytes)};\n")
        ofile_h.write("#else\n")
        ofile_h.write(f"static const size_t {name}_size={len(bytes)};\n")
        ofile_h.write("#endif\n")


def bin2s(input_paths: list[str], header_path: str|None) -> None:
    ofile_h = None

    if header_path is not None:
        ofile_h = ioutil.open_output(header_path)
        ofile_h.write("/* Generated by BIN2S - please don't edit directly */\n")
        ofile_h.write("#pragma once\n")
        ofile_h.write("#include <stddef.h>\n")
        ofile_h.write("#include <stdint.h>\n")
        ofile_h.write("\n")

    try:
        for input_path in input_paths:
            name = re.sub(r'[^A-Za-z0-9_]', '_', path.basename(input_path))
            with ioutil.open_input(input_path, binary=True) as ifile:
                process_file(name, ifile, ofile_h)

    finally:
        if ofile_h:
            ofile_h.close()


def main() -> None:
    global g_alignment, g_symbol_prefix, g_output_mode
    
    parser = argparse.ArgumentParser('bin2s',
                                     description="convert binary files to assembly language",
                                     usage="bin2s [option ...] [binary files ...]")
    parser.add_argument('-a', '--alignment',
                        metavar='ALIGN',
                        help='set parameter for .align')
    parser.add_argument('-H', '--header',
                        help='output C header')
    parser.add_argument('-r', '--arch',
                        help="target architecture (x86, arm, wasm)")
    parser.add_argument('--prefix',
                        help="symbol prefix")
    parser.add_argument('input',
                        metavar='binary file',
                        nargs='+',)
    
    args = parser.parse_args()

    if args.alignment is not None:
        g_alignment = int(args.alignment)
    
    if args.prefix is not None:
        g_symbol_prefix = args.prefix

    if args.arch is not None:
        match args.arch.lower():
            case "x86" | "arm":
                g_output_mode = "default"
            case "wasm":
                g_output_mode = "wasm"
            case _:
                sys.stderr.write(f"invalid architecture '{args.arch}'")
                exit(1)
        
    bin2s(args.input, args.header)


if __name__ == '__main__': main()